### ISSUE TITLE
Deployment documentation

### ISSUE THREAD

**Issue by PratikPramanik** [danilop/serverless-chat#1]
Just saw your talk at SFLoft. Would it be possible for you to cover the deployment process of an app like this? There is good number of AWS services this depends on, would be great to see how it all comes together on the console.

**Comment by BenLiyanage** [comment]
That would be awesome.  It'd also be great if you linked out to the running example you had setup, as I've been looking for that as well.

**Comment by danilop** [comment]
This is good feedback. I actually started working on a SAM/CloudFormation template to automate deployment.
